"""
Django settings for django_pays project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4tg@dddr)p5ndt!1e^c4%llsuv3@40)0@@7dxw6z++q&3fg_hz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'unionpays',
    'wxpays',
    'alipays',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_pays.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_pays.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# APPID
ALIPAY_APPID = "2021001157664176" # 沙箱APPID，生产环境须更改为应用APPID。

# 网关
# ALIPAY_URL = "https://openapi.alipaydev.com/gateway.do" # 沙箱网关，生产环境须更改为正式网关。
ALIPAY_URL = "https://openapi.alipay.com/gateway.do" # 正式网关，开发环境勿使用。

# 回调通知地址
# ALIPAY_NOTIFY_URL = "http://127.0.0.1:9999/pay_result/" # 如果只可以内网访问开发服务器
ALIPAY_NOTIFY_URL = "http://39.100.86.174/b_port/order/ali_pay_result/" # 如果生产环境或外网可以访问开发服务器
ALIPAY_RETURN_URL = "https://niceutp.com/merchant_system/transaction" # return_url可以单独设置，本文中保持一致。

# 使用密钥文件
APP_PRIVATE_KEY_PATH = os.path.join(BASE_DIR, 'order/app_private_key.txt')
ALIPAY_PUBLIC_KEY_PATH = os.path.join(BASE_DIR, 'order/alipay_public_key.txt')

# 使用密钥字符串
APP_PRIVATE_KEY = 'MIIEpAIBAAKCAQEAsePY5XirpP3bpaW6ec/qmF5cVjTCeL36Goy9U2wLLovGLO7x3h22giBqSK73Y779a6mnsWqasiSUIG2dn4GThcO+6Ga8WihRtjhlkkyq34NwVWJDz9nXrHska9qIfCxb/+AmLEIz4E4AmAy1M7hlUQu5feWrWFDvPmh+cspZmayYPVxpM7wL8+J8IPtK1/FOri/zSylQx7+JWvNuJ4fImv5EzpG3VP0lI4DpO7lUGaP7/KxsjxALDF7EHawxu0Ysb7Z/4vxkFtLLrK+6hWuXE5hqKuEpV7v+TN7/N9q2evU2VQzXATalITR8fRoLthVVAclDhaid/dlPkYVcLxvE1QIDAQABAoIBAFKCupIFXKgUz5KPwmTJ2ah+7BlYM3PJun4iFZbiIHWgg3VIB4vdAFBvNJ0t+rWbWvRbJtsV9Vb3vHUmItxfP8vltWEadfbjiLMaiZJIWWF/F9Wi1I1OH8ly/LvCC1h9Qtb2Yv5YXrOFuqTMEChDOUtUQt9wbf9y2uV5ll0sGk86hRvZeG9AWHcV2TgJtpO0XYE8G0HecslNYHPE2Hg4g421xkVYuLydF2Li/JHHe62HISeqiBVY8HoxbOvcOn2/PeDoezdT98jexbz4GlOpaPo1MogGKr0JniLb2OVv+/qyiDCQHavubOhyNQuMv3tZaJA9iEv5Mv54t23OPenb4cECgYEA9a3pa3VrmnupCD6L5FObFox/AI6MqtanqDxRPM6amk5VfdBU9X13PU8yd15rBzKOAZSEJkq3s/bWNs++eGeY1OwARgzA5oLcNiYHsVrDkbFic+vRzNQ4ukD9jA4ALevfFc9Fuaz3ELZwlzipTtDwiP2bo0hZRIZqiKEVqq75h30CgYEAuVzqJ48c7BfPrLs3X++nYGPnt9pkp+XOlGxAxQUJ/BIzwDZznWYV4aGWn15Ovi5+iPpb6vpPf7vtpwNe8OjgZZPLR2WxYjew/+jwGNUyMobTkxAt8TZZ2vUkeJfQyT97KXlT/T4MVevgOurJI6NLznp3oWfk0ylZmyR3vy0mIjkCgYEAoLrSx1beuwbEI3yoEQ0RncL1I+we43Xj4hD0JRAV3XX6QIGX07Pt2tKBdc7zvpW4ihgcDOE9JiQLKXjoZ+V++24bD7kwSp66a0KeLc3vvNWMT8KsU5FUO6ZhOsu+Gk0CekZMm5kpWmnBZ23Odp4Df9xLgpvGqyo1cIXSowQuhBECgYA0sr2/UWifloVsTi2IENI9DSorkuNa+HKqr7waRzx3dZVQ6CombYd7Bj2UQXORjhZbSxIm09MWNY9zE/pB83MYbdQ1ECxGCB9CIi9gX/xNcRdlkAv/r7wMC/W6cy7giDOzrtK6BJHtO4ocNfPJNfuvUBICyU682dynxs5kg6l7wQKBgQCj5CQW9B/WfVW0oirBjjacQlrCIgRhtaIhXYD3GQB+47FJ29eMNUSAT+dd3ChH0ye69hep6D31L1d/xLLf0Bao+pt0Qi6gXIVRildpcsXc8rZM2ZLW4JUR7NknLB+AlW8yZ+joBqf3LF1Kk5kQjUZYurXt3pATG1RqViCfX5uWwQ=='
ALIPAY_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhjVPARjMNrqkvSwTHsMvWXsA63msOyf8qkdOZ+oHalttZADVN3z+LFcy6xETgXT3NONScCnyodngWAt5G7XiptmM5M/gH+OlmUtUKgj/rIK7i6iSsS/3knyOGHso2hVXEIx6tHIGTLvfJCjux8OaoqhmbQqswdv+orxu98QZTDpIgSoHOkPsL+xKiLbtSZBcba9vr9A713jVOOrP277lzaGtbWKaSb8BqRM4FLrDNVNctWBzTXQ+F7d+cruAFzoodDcf38+M5px8bTNy1fsp5bir+0zbQPREYI6BVemIKM3/jgYu6k8e1CMAQvgpSQnT5SSsFtdh7t7WsG7oZ7EKuQIDAQAB'